# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
one_dim_arr = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
two_dim_arr = np.array([[1,2,3], [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
three_dim_arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])

one_dim_arr.ndim, two_dim_arr.ndim, three_dim_arr.ndim

(1, 2, 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_dim_arr.ndim, one_dim_arr.dtype, one_dim_arr.size, type(one_dim_arr)

(1, dtype('int64'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
two_dim_arr.ndim, two_dim_arr.dtype, two_dim_arr.size, type(two_dim_arr)

(2, dtype('int64'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
three_dim_arr.ndim, three_dim_arr.dtype, three_dim_arr.size, type(three_dim_arr)

(3, dtype('int64'), 12, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df_array = pd.DataFrame(two_dim_arr)
df_array

0  1  2
0  1  2  3
1  4  5  6

In [8]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
step_arr = np.array(range(0, 100, 3))
step_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_arr = np.random.randint(0, 10, (7,2))
random_arr

array([[6, 3],
       [1, 3],
       [7, 6],
       [4, 5],
       [5, 7],
       [1, 3],
       [8, 1]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float_arr = np.random.random((3,5))
random_float_arr

array([[0.32758227, 0.34458798, 0.76390792, 0.62557824, 0.42084445],
       [0.99569725, 0.5578687 , 0.81893   , 0.24581028, 0.37027181],
       [0.81947633, 0.5281275 , 0.61746366, 0.64205214, 0.07415398]])

In [15]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_int_arr = np.random.randint(0, 10, (4,6))
random_int_arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [17]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
int_array = np.random.randint(1,10,(3,7))

# Find the unique numbers in the array you just created
int_array, np.unique(int_array)

(array([[7, 8, 3, 1, 4, 2, 8],
        [4, 2, 6, 6, 4, 6, 2],
        [2, 4, 8, 7, 9, 8, 5]]),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [18]:
# Find the 0'th index of the latest array you created
int_array[0]

array([7, 8, 3, 1, 4, 2, 8])

In [19]:
# Get the first 2 rows of latest array you created
int_array[:2]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [21]:
# Get the first 2 values of the first 2 rows of the latest array
int_array[:2,:2]

array([[7, 8],
       [4, 2]])

In [25]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand_0_10 = np.random.randint(10, size=(3,5))
ones_arr = np.ones((3,5))
rand_0_10 , ones_arr

(array([[7, 9, 8, 8, 0],
        [8, 6, 8, 7, 0],
        [7, 7, 2, 0, 7]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [26]:
# Add the two arrays together
rand_0_10 + ones_arr

array([[ 8., 10.,  9.,  9.,  1.],
       [ 9.,  7.,  9.,  8.,  1.],
       [ 8.,  8.,  3.,  1.,  8.]])

In [27]:
# Create another array of ones of shape (5, 3)
another_ones_arr = np.ones((5,3))

In [29]:
# Try add the array of ones and the other most recent array together
another_ones_arr + rand_0_10.reshape((5,3))

array([[ 8., 10.,  9.],
       [ 9.,  1.,  9.],
       [ 7.,  9.,  8.],
       [ 1.,  8.,  8.],
       [ 3.,  1.,  8.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [30]:
# Create another array of ones of shape (3, 5)
arr_3_5 = np.random.randint(10, size=(3,5))

In [32]:
# Subtract the new array of ones from the other most recent array
new_ones_arr = np.ones((3,5))
new_ones_arr - arr_3_5

array([[-1., -1.,  1., -3., -8.],
       [-5., -8., -7., -5., -7.],
       [-6.,  0.,  1., -5., -5.]])

In [33]:
# Multiply the ones array with the latest array
new_ones_arr * arr_3_5

array([[2., 2., 0., 4., 9.],
       [6., 9., 8., 6., 8.],
       [7., 1., 0., 6., 6.]])

In [35]:
# Take the latest array to the power of 2 using '**'
arr_3_5 ** 2

array([[ 4,  4,  0, 16, 81],
       [36, 81, 64, 36, 64],
       [49,  1,  0, 36, 36]])

In [36]:
# Do the same thing with np.square()
np.square(arr_3_5)

array([[ 4,  4,  0, 16, 81],
       [36, 81, 64, 36, 64],
       [49,  1,  0, 36, 36]])

In [37]:
# Find the mean of the latest array using np.mean()
np.mean(arr_3_5)

4.933333333333334

In [39]:
# Find the maximum of the latest array using np.max()
arr_3_5, np.max(arr_3_5)

(array([[2, 2, 0, 4, 9],
        [6, 9, 8, 6, 8],
        [7, 1, 0, 6, 6]]),
 9)

In [40]:
# Find the minimum of the latest array using np.min()
np.min(arr_3_5)

0

In [41]:
# Find the standard deviation of the latest array
np.std(arr_3_5)

3.0868898407440604

In [42]:
# Find the variance of the latest array
np.var(arr_3_5)

9.528888888888892

In [43]:
# Reshape the latest array to (3, 5, 1)
arr_3_5.reshape((3,5,1))

array([[[2],
        [2],
        [0],
        [4],
        [9]],

       [[6],
        [9],
        [8],
        [6],
        [8]],

       [[7],
        [1],
        [0],
        [6],
        [6]]])

In [44]:
# Transpose the latest array
arr_3_5.T

array([[2, 6, 7],
       [2, 9, 1],
       [0, 8, 0],
       [4, 6, 6],
       [9, 8, 6]])

What does the transpose do?

In [45]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr_1 = np.random.randint(10, size=(3,3))
arr_2 = np.random.randint(10, size=(3,2))

In [47]:
# Perform a dot product on the two newest arrays you created
arr_1.dot(arr_2)

array([[42, 48],
       [46, 57],
       [32, 42]])

In [48]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr_1 = np.random.randint(10, size=(4,3))
arr_2 = np.random.randint(10, size=(4,3))

In [50]:
# Perform a dot product on the two newest arrays you created
arr_1.dot(arr_2.T)

array([[111, 161, 104, 198],
       [ 24,  56,  38,  54],
       [ 44,  62,  39,  77],
       [ 63,  84,  63, 114]])

It doesn't work. How would you fix it?

In [51]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr_1.dot(arr_2.T)

array([[111, 161, 104, 198],
       [ 24,  56,  38,  54],
       [ 44,  62,  39,  77],
       [ 63,  84,  63, 114]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr_1 = np.random.randint(10, size=(4,3))
arr_2 = np.random.randint(10, size=(4,3))

In [52]:
# Compare the two arrays with '>'
arr_1 > arr_2

array([[ True,  True,  True],
       [ True, False, False],
       [False, False,  True],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [53]:
# Compare the two arrays with '>='
arr_1 >= arr_2

array([[ True,  True,  True],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False]])

In [60]:
# Find which elements of the first array are greater than 7
arr_1 > 7

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [59]:
# Which parts of each array are equal? (try using '==')
arr_1 == arr_2

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [62]:
# Sort one of the arrays you just created in ascending order
arr_1, np.sort(arr_1)

(array([[8, 9, 9],
        [2, 6, 0],
        [3, 3, 4],
        [6, 6, 3]]),
 array([[8, 9, 9],
        [0, 2, 6],
        [3, 3, 4],
        [3, 6, 6]]))

In [64]:
# Sort the indexes of one of the arrays you just created
arr_1, np.argsort(arr_1)

(array([[8, 9, 9],
        [2, 6, 0],
        [3, 3, 4],
        [6, 6, 3]]),
 array([[0, 1, 2],
        [2, 0, 1],
        [0, 1, 2],
        [2, 0, 1]]))

In [65]:
# Find the index with the maximum value in one of the arrays you've created
arr_1, np.argmax(arr_1)

(array([[8, 9, 9],
        [2, 6, 0],
        [3, 3, 4],
        [6, 6, 3]]),
 1)

In [66]:
# Find the index with the minimum value in one of the arrays you've created
arr_1, np.argmin(arr_1)

(array([[8, 9, 9],
        [2, 6, 0],
        [3, 3, 4],
        [6, 6, 3]]),
 5)

In [67]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
arr_1, np.argmax(arr_1, axis=1)

(array([[8, 9, 9],
        [2, 6, 0],
        [3, 3, 4],
        [6, 6, 3]]),
 array([1, 1, 2, 0]))

In [68]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
arr_1, np.argmin(arr_1, axis=0)

(array([[8, 9, 9],
        [2, 6, 0],
        [3, 3, 4],
        [6, 6, 3]]),
 array([1, 2, 1]))

In [69]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[-0.70205309, -0.32766215, -0.39210815, -1.46351495,  0.29612028],
       [ 0.26105527,  0.00511346, -0.23458713, -1.41537074, -0.42064532],
       [-0.34271452, -0.80227727, -0.16128571,  0.40405086,  1.8861859 ]])

In [73]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.